import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {GraphQLClient, gql} from 'graphql-request';
import ProjectCard from '../components/ProjectCard';

const graphcms = new GraphQLClient(
  "https://api-eu-central-1.graphcms.com/v2/cl487ukop4j4101ywhu54g7ml/master"
);

const QUERY = gql`
  {
    projects{
      id,
      title,
      slug,
      datePublished,
      content{
        html 
      },
      project_type{
        name 
        avatar{
          url 
        }
      }
      coverPhoto{
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { projects } = await graphcms.request(QUERY);
  return {
    props: {
      projects,
    },
    revalidate: 10,
  };
}

export default function Home({projects}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {projects.map((project) => (
          <ProjectCard 
            title={project.title} 
            project_type={project.project_type} 
            coverPhoto={project.coverPhoto} 
            key={project.id} 
            datePublished={project.datePublished} 
            slug={project.slug}
          />
        ))}
      </main>

    </div>
  )
}
